export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const DIAL_NUMBER = 'DIAL_NUMBER';
export const CALL_NEW_SUCCESS = 'CALL_NEW_SUCCESS';
export const CALL_NEW_ERROR = 'CALL_NEW_ERROR';
export const CALL_TALK_SUCCESS = 'CALL_TALK_SUCCESS';
export const CALL_TALK_ERROR = 'CALL_TALK_ERROR';
export const CALL_END_SUCCESS = 'CALL_END_SUCCESS';
export const CALL_END_ERROR = 'CALL_END_ERROR';
export const CALL_HOLD_SUCCESS = 'CALL_HOLD_SUCCESS';
export const CALL_HOLD_ERROR = 'CALL_HOLD_ERROR';
export const CALL_PAUSE_RECORDING_SUCCESS = 'CALL_PAUSE_RECORDING_SUCCESS';
export const CALL_PAUSE_RECORDING_ERROR = 'CALL_PAUSE_RECORDING_ERROR';
export const CALL_RESUME_RECORDING_SUCCESS = 'CALL_RESUME_RECORDING_SUCCESS';
export const CALL_RESUME_RECORDING_ERROR = 'CALL_RESUME_RECORDING_ERROR';
export const CALL_START_RECORDING_SUCCESS = 'CALL_START_RECORDING_SUCCESS';
export const CALL_START_RECORDING_ERROR = 'CALL_START_RECORDING_ERROR';
export const CALL_STOP_RECORDING_SUCCESS = 'CALL_STOP_RECORDING_SUCCESS';
export const CALL_STOP_RECORDING_ERROR = 'CALL_STOP_RECORDING_ERROR';
export const CALL_TRANSFER_SUCCESS = 'CALL_TRANSFER_SUCCESS';
export const CALL_TRANSFER_ERROR = 'CALL_TRANSFER_ERROR';
export const CALL_START_CONFERENCE_SUCCESS = 'CALL_START_CONFERENCE_SUCCESS';
export const CALL_START_CONFERENCE_ERROR = 'CALL_START_CONFERENCE_ERROR';


export const SAVE_WEBSOCKET = 'SAVE_WEBSOCKET';

export const CALL_END_COMPLETE_SUCCESS = 'CALL_END_COMPLETE_SUCCESS';
export const CALL_END_COMPLETE_ERROR = 'CALL_END_COMPLETE_ERROR';


export const INIT_SUCCESS = 'INIT';


export const STATUS = {
    SIGN_IN: "SIGN_IN",
    SIGNED_IN: "SIGNED_IN",
    CALL_CONTROLLER: "CALL_CONTROLLER",
    TRANSFER_KEYPAD: "TRANSFER_KEYPAD"
};

export const CALL_EVENTS = {
    CALL_ORIGINATING_EVENT: 'CALL_ORIGINATING_EVENT',
    CALL_ORIGINATED_EVENT: 'CALL_ORIGINATED_EVENT',
    CALL_COLLECTING_EVENT: 'CALL_COLLECTING_EVENT',
    CALL_RECEIVED_EVENT: 'CALL_RECEIVED_EVENT',
    CALL_ANSWERED_EVENT: 'CALL_ANSWERED_EVENT',
    CALL_RELEASED_EVENT: 'CALL_RELEASED_EVENT',
    CALL_HELD_EVENT: 'CALL_HELD_EVENT',
    CALL_RECORDING_STOPPED_EVENT: 'CALL_RECORDING_STOPPED_EVENT',
    CALL_RETRIEVED_EVENT: 'CALL_RETRIEVED_EVENT',
    CALL_REDIRECTED_EVENT: 'CALL_REDIRECTED_EVENT'
}

export const WebSocketStates = {
    CONNECTING: 0,
    OPEN: 1,
    CLOSING: 2,
    CLOSED: 3
}